
-- DROP das tabelas na ordem correta
DROP TABLE ITEM_VENDA CASCADE CONSTRAINTS;
DROP TABLE VENDA CASCADE CONSTRAINTS;
DROP TABLE PRODUTO CASCADE CONSTRAINTS;
DROP TABLE SERVICO CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE CARGO CASCADE CONSTRAINTS;
DROP TABLE LOJA CASCADE CONSTRAINTS;
DROP TABLE AUDITORIA_VENDA CASCADE CONSTRAINTS;
