-- Trigger de auditoria
CREATE OR REPLACE TRIGGER TR_AUDITORIA_VENDA
AFTER INSERT OR DELETE OR UPDATE ON VENDA
FOR EACH ROW
DECLARE
    v_acao VARCHAR2(20);
BEGIN
    IF INSERTING THEN
        v_acao := 'INSERÇÃO';
    ELSIF UPDATING THEN
        v_acao := 'ATUALIZAÇÃO';
    ELSIF DELETING THEN
        v_acao := 'REMOÇÃO';
    END IF;

    INSERT INTO AUDITORIA_VENDA (ACAO, ID_VENDA, USUARIO)
    VALUES (v_acao, :NEW.ID_VENDA, USER);
END;
