
-- Criação das tabelas
CREATE TABLE LOJA (
    ID_LOJA NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    ENDERECO VARCHAR2(200),
    TELEFONE VARCHAR2(20)
);

CREATE TABLE CARGO (
    ID_CARGO NUMBER PRIMARY KEY,
    NOME_CARGO VARCHAR2(50)
);

CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CPF VARCHAR2(14) UNIQUE,
    DATA_ADMISSAO DATE,
    SALARIO NUMBER(10,2),
    ID_CARGO NUMBER,
    ID_LOJA NUMBER,
    FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
    FOREIGN KEY (ID_LOJA) REFERENCES LOJA(ID_LOJA)
);

CREATE TABLE CLIENTE (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CPF VARCHAR2(14) UNIQUE,
    EMAIL VARCHAR2(100)
);

CREATE TABLE PRODUTO (
    ID_PRODUTO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    PRECO NUMBER(10,2),
    ESTOQUE NUMBER,
    CATEGORIA VARCHAR2(50)
);

CREATE TABLE SERVICO (
    ID_SERVICO NUMBER PRIMARY KEY,
    DESCRICAO VARCHAR2(100),
    PRECO NUMBER(10,2),
    TIPO VARCHAR2(50)
);

CREATE TABLE VENDA (
    ID_VENDA NUMBER PRIMARY KEY,
    ID_CLIENTE NUMBER,
    ID_FUNCIONARIO NUMBER,
    ID_LOJA NUMBER,
    DATA_VENDA DATE,
    VALOR_TOTAL NUMBER(10,2),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
    FOREIGN KEY (ID_LOJA) REFERENCES LOJA(ID_LOJA)
);

CREATE TABLE ITEM_VENDA (
    ID_VENDA NUMBER,
    ID_PRODUTO NUMBER,
    QUANTIDADE NUMBER,
    PRECO_UNITARIO NUMBER(10,2),
    FOREIGN KEY (ID_VENDA) REFERENCES VENDA(ID_VENDA),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO),
    PRIMARY KEY (ID_VENDA, ID_PRODUTO)
);

CREATE TABLE AUDITORIA_VENDA (
    ID_AUDITORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ACAO VARCHAR2(20),
    ID_VENDA NUMBER,
    DATA_MODIFICACAO DATE DEFAULT SYSDATE,
    USUARIO VARCHAR2(50)
);